### ISSUE TITLE
Post upgrade to 0.1.2 Test Metrics columns not reporting proper data. 

### ISSUE THREAD

**Issue by aniketnjoshi** [adiralashiva8/robotframework-historic#10]
Post upgrade from 0.1.1 to 0.1.2 version, Test metrics column headers and data is not matching for already imported reports.
PFA screenshot for more details.

![rfhistoric-TestMetricsIssue](https://user-images.githubusercontent.com/34476763/75151537-ec213c00-572c-11ea-80b1-9a90d4ec7673.png)

**Comment by adiralashiva8** [comment]
Thanks for upgrading,

**Root Cause for Issue:** There are 2 new columns added in test_results table (v0.1.2 ) so there is mismatch in column and its values

**Action:** For existing project users must add column by own. Please refer to steps mention in [link](https://github.com/adiralashiva8/robotframework-historic#existing-users) for adding columns manully

Do let me know

**Comment by aniketnjoshi** [comment]
Thanks for your support.
