### ISSUE TITLE
Unable to create data base  with command:  rfhistoric

### ISSUE THREAD

**Issue by nikhileshkoshti** [adiralashiva8/robotframework-historic#11]
I followed the same path mentioned in `https://github.com/adiralashiva8/robotframework-historic`.
And, when I execute the command:- rfhistoric, it opened the page , however, after clicking on `Get Started`, I received the error :- 
**Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**

And on the terminal output:-

    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1055, "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.tables.CREATE_TIME' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
127.0.0.1 - - [24/Feb/2020 18:58:11] "GET /home HTTP/1.1" 500 -

**Comment by adiralashiva8** [comment]
Thanks for try.

**Root Cause:** MySQL DB is not installed or MySQL dB url is incorrect

**Action** Follow the steps mentioned in https://github.com/adiralashiva8/robotframework-historic#installation

**Note**: Please go through each and every link (guide) included in installation which guides you to setup successfully

Do let me know how it goes

**Comment by nikhileshkoshti** [comment]
Thank you, the SQL installation was corrupted. Reinstall the MySQL and everything works as expected. Tool is amazing. :)

**Comment by nikhileshkoshti** [comment]
No issue found.
